version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nesbot/carbon
    versions:
    - 2.43.0
    - 2.44.0
    - 2.45.0
    - 2.45.1
