version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - ./:/app/
      - $HOME/.config/composer/:/tmp/composer/
    environment:
      VIRTUAL_PORT: 80
      POSTFIX_RELAYHOST: "[mail]:1025"
      PHP_IDE_CONFIG: "serverName=app"
      COMPOSER_HOME: /tmp/composer/

  mail:
    image: mailhog/mailhog
    environment:
      - VIRTUAL_PORT=8025
